name: ci_linters_windows
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - main
      - develop
      - trying
      - staging
      - 'rc/*'
jobs:
  prologue:
    name: prologue
    runs-on: ubuntu-20.04
    outputs:
      os_skip: ${{ steps.prologue.outputs.os_skip }}
      job_skip: ${{ steps.prologue.outputs.job_skip }}
      uses_self_runner: ${{ steps.prologue.outputs.ci_uses_self_runner }}
    steps:
    - name: prologue
      id: prologue
      uses: liya2017/composite-action@v1
      with:
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        COMMIT_MESSAGE: "${{github.event.head_commit.message}}"
        PR_COMMONS_BODY: "${{ github.event.pull_request.body }}"
        GITHUB_TOKEN: ${{secrets.WORKFLOW_TOKEN}}
        LABELS: "${{ toJson(github.event.pull_request.labels.*.name) }}"
        GITHUB_REPOSITORY: ${{ github.repositoty }}
        GITHUB_WORKFLOW: ${{ github.workflow }}
    - run: |
        echo ${{ steps.prologue.outputs.os_skip }}
        echo ${{ steps.prologue.outputs.job_skip }}
        echo ${{ steps.prologue.outputs.runner_label }}
      shell: bash
  ci_liners:
    name: ci_liners
    needs: prologue
    runs-on: windows-2019
    if: needs.prologue.outputs.os_skip == 'run' && needs.prologue.outputs.job_skip == 'run' 
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo ${{ needs.prologue.outputs.os_skip }}
        echo ${{ needs.prologue.outputs.job_skip }}
        echo ${{ needs.prologue.outputs.runner_label }}
        devtools/ci/ci_main.sh
      shell: bash

    # - name: install python requirements
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: 3.8
    # - run: |
    #     pip install requests
    #     pip install datetime
    #     pip install python-dotenv
    #     pip install PyGithub
    # - name: ci_epilogue
    #   id: ci_epilogue
    #   uses: liya2017/composite-action@v1
    #   with:
    #       who-to-greet: 'Mona the Octocat'
    # - run: |
    #     python3 ${{ github.workspace }}/devtools/ci/ci_epilogue.py > result.log
    #     cat result.log