name: ci_alert
on:
  workflow_run:
    workflows: ["ci_unit_tests","ci_linters"]
    branches: [main]
    types: 
      - completed
jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo "failure"