name: ci_unit_tests_windows
concurrency:
  group: ci_unit_tests_windows-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - main
      - develop
      - trying
      - staging
      - 'rc/*'
jobs:
  prologue:
    name: prologue
    runs-on: ubuntu-20.04
    outputs:
      os_skip: ${{ steps.prologue.outputs.os_skip }}
      job_skip: ${{ steps.prologue.outputs.job_skip }}
      uses_self_runner: ${{ steps.prologue.outputs.ci_uses_self_runner }}
    steps:
    - uses: actions/checkout@v2
    - name: prologue
      id: prologue
      uses: ./.github/actions/ci_prologue
      with:
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        COMMIT_MESSAGE: "${{github.event.head_commit.message}}"
        PR_COMMONS_BODY: "${{ github.event.pull_request.body }}"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LABELS: "${{ toJson(github.event.pull_request.labels.*.name) }}"
        GITHUB_REPOSITORY: ${{ github.repositoty }}
        GITHUB_WORKFLOW: ${{ github.workflow }}
        GITHUB_ACTOR: ${{ github.actor }}
    - run: |
        echo ${{ steps.prologue.outputs.os_skip }}
        echo ${{ steps.prologue.outputs.job_skip }}
        echo ${{ steps.prologue.outputs.runner_label }}
      shell: bash

  ci_unit_tests_windows:
    name: ci_unit_tests_windows
    needs: prologue
    runs-on: windows-2019
    if: needs.prologue.outputs.os_skip == 'run' && needs.prologue.outputs.job_skip == 'run'
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo ${{ needs.prologue.outputs.os_skip }}
        echo ${{ needs.prologue.outputs.job_skip }}
        echo ${{ needs.prologue.outputs.runner_label }}
        devtools/ci/ci_main.sh
        sleep 960
      shell: bash
    env:
      RUNNER_LABEL: ${{ needs.prologue.outputs.runner_label }}



  
